ProjectDefence/Controllers/HomeController.cs
using Interfaces;
using Microsoft.AspNetCore.Mvc;
using ProjectDefence.Models;
using System.Diagnostics;

namespace ProjectDefence.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IPostService _postService;

        public HomeController(ILogger<HomeController> logger, IPostService postService)
        {
            _logger = logger;
            _postService = postService;
        }

        public async Task<IActionResult> Index()
        {
            var model = await _postService.GetLastFourPosts();
            return View(model);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProjectDefence/Controllers/PostController.cs
using DataModels.Models;
using Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace ProjectDefence.Controllers
{
    public class PostController : Controller
    {
        private readonly IPostService _postService;
        public PostController(IPostService postService)
        {
            _postService = postService;
        }

        public async Task<IActionResult> GetFullPost(int postId)
        {
            var model = await _postService.GetFullPostAsync(postId);
            if (model == null)
            {
                return RedirectToAction("NotFound", "Error");
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> GetAllArticles()
        {
            var model = await _postService.GetAllPosts();
            if (model == null)
            {
                return RedirectToAction("NotFound", "Error");
            }
            return View(model);
        }
    }
}

ProjectDefence/Controllers/TrainerApplicationController.cs
using DataModels.Entities;
using DataModels.Models;
using Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace ProjectDefence.Controllers
{
    [Authorize(Roles = "Client")]
    public class TrainerApplicationController : Controller
    {
        private readonly IApplicationFormService _applicationForm;

        public TrainerApplicationController(IApplicationFormService applicationForm)
        {
            _applicationForm = applicationForm;
        }
        [HttpGet]
        public IActionResult ApplicationFormForTrainers()
        {
            if (User?.Identity?.IsAuthenticated ?? false)
            {
                var model = new ApplicationFormForTrainersViewModel();
                return View(model);
            }

            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> ApplicationFormForTrainers(ApplicationFormForTrainersViewModel model)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            await _applicationForm.CreateApplicationAsync(model, userId);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult CancelForm()
        {
            return RedirectToAction("Index", "Home");
        }
    }
}

ProjectDefence/Views/Home/Index.cshtml
@using DataModels.Entities
@using DataModels.Models
@using Microsoft.AspNetCore.Identity
@inject UserManager<User> userManager
@inject SignInManager<User> SignInManager
@model IEnumerable<PostViewModel>
@{
    ViewData["Title"] = "Home Page";
}

@if (SignInManager.IsSignedIn(User))
{
    if ((User?.IsInRole("Administrator") ?? false) && (User?.IsInRole("Client") ?? false))
    {
        <div class="card col-4" style="width: 20rem; margin-bottom:100px; left: 90%">
            <a class="btn btn-sm btn-warning" asp-controller="TrainerApplication" asp-action="ApplicationFormForTrainers">Wanna be Trainer? Join Us Now!</a>
        </div>
    }
    else if ((User?.IsInRole("Client") ?? false) && (User?.IsInRole("Trainer") == false))
    {
        <div class="card col-4" style="width: 20rem; margin-bottom:100px; left: 90%;">
            <a class="btn btn-sm btn-warning" asp-controller="TrainerApplication" asp-action="ApplicationFormForTrainers">Wanna be Trainer? Join Us Now!</a>
        </div>
    }
    else
    {
        <partial name="_TrainerInfoPartial" />
        <div class="card col-4" style="width: 20rem; margin-bottom:100px; left: 90%">
            <a class="btn btn-sm btn-info" asp-controller="Trainers" asp-action="GetClients" style='font-size:20px'>You are a Trainer! Check Your Clients! <i class='far fa-handshake'></i></a>
        </div>
    }
}

<h1 class="text-center">Welcome To Fitness App PROJECT DEFENCE</h1>
<hr />
<div class="time">
    <span class="hms"></span>
    <span class="ampm"></span>
    <br>
    <span class="date"></span>
</div>
<br>
<div class="text-center row">

    <br>
    <br>
    <div class="text-center row">
        <br>
        <br>
        @foreach (var post in Model)
        {
            <div class="card col-4" style="width: 19rem; margin-right: 20px; margin: 5px">
                <div class="card-body">

                    <h5 class="card-title mt-1">@post.Title</h5>
                    <p class="mb-0">Published On: @post.DatePublishedOn</p>
                    <hr />
                    <p class="mb-0">@post.Text</p>
                </div>

                <form class="input-group-sm" asp-controller="Post" asp-action="GetFullPost" asp-route-postId="@post.Id">
                    <input type="submit" value="Read More" class="fs-6 btn btn-success mb-3 p-2" />
                </form>
            </div>
            <br>
        }
    </div>
</div>

<div class="text-center row" style="margin-top: 30%">
    <form class="input-group-sm" asp-controller="Post" asp-action="GetAllArticles">
        <input type="submit" value="Load All Articles" class="fs-6 btn btn-link mb-3 p-2" />
    </form>
</div>

@*Icon Source:https://www.w3schools.com/icons/tryit.asp?icon=fas_fa-handshake&unicon=f2b5 *@
<script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>

<script>
     function updateTime() {
  var dateInfo = new Date();

  /* time */
  var hr,
    _min = (dateInfo.getMinutes() < 10) ? "0" + dateInfo.getMinutes() : dateInfo.getMinutes(),
    sec = (dateInfo.getSeconds() < 10) ? "0" + dateInfo.getSeconds() : dateInfo.getSeconds(),
    ampm = (dateInfo.getHours() >= 12) ? "PM" : "AM";

  // replace 0 with 12 at midnight, subtract 12 from hour if 13–23
  if (dateInfo.getHours() == 0) {
    hr = 12;
  } else if (dateInfo.getHours() > 12) {
    hr = dateInfo.getHours() - 12;
  } else {
    hr = dateInfo.getHours();
  }

  var currentTime = hr + ":" + _min + ":" + sec;

  // print time
  document.getElementsByClassName("hms")[0].innerHTML = currentTime;
  document.getElementsByClassName("ampm")[0].innerHTML = ampm;

  /* date */
  var dow = [
      "Sunday",
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday"
    ],
    month = [
      "January",
      "February",
      "March",
      "April",
      "May",
      "June",
      "July",
      "August",
      "September",
      "October",
      "November",
      "December"
    ],
    day = dateInfo.getDate();

  // store date
  var currentDate = dow[dateInfo.getDay()] + ", " + month[dateInfo.getMonth()] + " " + day;

  document.getElementsByClassName("date")[0].innerHTML = currentDate;
};

// print time and date once, then update them every second
updateTime();
setInterval(function() {
  updateTime()
}, 1000);
</script>

@*
    The watch has been taken from this web site:
https://www.foolishdeveloper.com/2021/06/how-to-create-digital-clock-with-date.html*@