ProjectDefence/Controllers/ExerciseController.cs
using Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace ProjectDefence.Controllers
{
    public class ExerciseController : Controller
    {
        private readonly IExerciseService _exerciseService;
        public ExerciseController(IExerciseService exerciseService)
        {
            _exerciseService = exerciseService;
        }

        [HttpGet]
        public async Task<IActionResult> AllExercises()
        {
            var model = await _exerciseService.GetAllExercisesAsync();

            return View(model);
        }

        public async Task<IActionResult> GetExercise(int exerciseId)
        {
            if (exerciseId == null)
            {
                return RedirectToAction("BadRequest", "Error");
            }

            var model = await _exerciseService.GetExerciseAsync(exerciseId);

            if (model == null)
            {
                return RedirectToAction("NotFound", "Error");
            }

            return View(model);
        }
    }
}

ProjectDefence/Controllers/GymsController.cs
using Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ProjectDefence.Controllers
{
    [Authorize]
    public class GymsController : Controller
    {
        private readonly IGymService _gymService;
        public GymsController(IGymService gymService)
        {
            _gymService = gymService;
        }

        [HttpGet]
        public async Task<IActionResult> All()
        {
            var model = await _gymService.GetAllGymsAsync();
            return View(model);
        }
    }
}

ProjectDefence/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjectDefence</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjectDefence.styles.css" asp-append-version="true" />
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
</head>
<body style="background-color: PaleTurquoise;">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid" style="background-color: lightblue;">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProjectDefence</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (User?.Identity?.IsAuthenticated ?? false)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Gyms" asp-action="All">Gyms</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Trainers" asp-action="AllTrainers">Trainers</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Exercise" asp-action="AllExercises">Exercises</a>
                            </li>

                            @if (User?.IsInRole("Administrator") ?? false)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Admin" asp-action="AdminPanel">Admin Panel</a>
                                </li>
                            }
                            @if (User?.IsInRole("Writer") ?? false)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="Writer" asp-controller="Writer" asp-action="GetWriterScreen">Writer Zone</a>
                                </li>
                            }
                        }

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ProjectDefence - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ProjectDefence/Views/Shared/_TrainerInfoPartial.cshtml
@using DataModels.Entities
@using DataModels.Models

<div class="card col-0" style="width: 14rem; left: 90%; background-color: PaleTurquoise; border-color:PaleTurquoise;">
    <a id="clicked" onclick="alert('You changed your availability!')" asp-controller="Trainers" asp-action="GetCountClients" class="btn btn-danger mb-3" >Change Your Availability</a>
</div>

<script>
$(document).ready(function(){
  $("a").click(function(){
    $("#clicked").click();
  });
});
</script>